# Generated by Django 4.1.3 on 2023-02-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0002_preaduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('end_date', models.DateField()),
                ('run_imm', models.BooleanField()),
            ],
            options={
                'db_table': 'job_schedules',
            },
        ),
        migrations.DeleteModel(
            name='schedule_job',
        ),
    ]
