# Generated by Django 4.1.3 on 2023-02-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0003_schedule_jobs_delete_schedule_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='config_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatype',
            name='datatype_mapping_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatype',
            name='source_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatype',
            name='source_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatype',
            name='target_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatype',
            name='target_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
