# Generated by Django 4.1.3 on 2023-02-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0004_alter_datatype_config_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_details',
            name='sql_extract_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
