# Generated by Django 4.1.3 on 2023-02-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0005_alter_pipeline_details_sql_extract_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline_details',
            name='sql_extract_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
