# Generated by Django 4.1.3 on 2023-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0006_alter_pipeline_details_sql_extract_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('employee_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_api',
            },
        ),
    ]
